### ISSUE TITLE
Where is the source code for Spydish.exe ?

### ISSUE THREAD

**Issue by DBJDBJ** [builtbybel/spydish#11]
I can not find it ...

**Comment by Belim** [comment]
not open (as yet)

**Comment by DBJDBJ** [comment]
Ah? That's a shame ... Gut-wrenching app of my windows machine which is not open-sourced ... Hmm.

It seems just a script runner ... what is stopping you to open it? 

What is it written in? VB6, Delphi :) ?

**Comment by Belim** [comment]
> It seems just a script runner ... what is stopping you to open it?
Nothing but time maybe, it was an old customer project.

> What is it written in? VB6, Delphi :) ?
This time i did it right (i think) 😁 Actually it's C#

The previous [Debotnet](https://github.com/builtbybel/debotnet) app was indeed compiled with Vb6. [Source](https://github.com/builtbybel/debotnet/tree/master/src/Debotnet) is available too, as I've discontinued the development
